[[plugins]]
package = "netlify-plugin-gatsby-cache"

package = "netlify-plugin-rss"
  [plugins.inputs]
  # required configs, customize as needed
  dirToScan = "/organizations" # a subfolder to scan. "/" to scan all
  authorName = "GoodHere.org"
  site_url = "https://goodhere.org"
  title = "GoodHere.org RSS Feed"
  rssDescription = "GoodHere.org RSS Feed"
  categories = ['Social Impact', 'Startups', 'Funding']

  # # optional configs, defaults shown
  # rssFaviconUrl = "https://swyx.io/favicon.png"
  # docs = "http://example.com/rss/docs.html"
  # managingEditor = "authorName"
  # webMaster = "authorName"
  # copyright = "2020 ${authorName}"
  # language = "en"
  # pubDate = "new Date().toUTCString(),"
  # ttl = "60" # aka refresh every hour

  # # cheerio selectors for extractMetadataFromFile
  # # defaults shown
  # contentSelector = "main"
  # publishDateSelector = # if not specified, we use the date of file creation
  # descriptionSelector = "meta[name=description]" # probably no need to change
  # titleSelector = "title" # probably no need to change

  # # developer configs
  # debugMode = false # (for development) turn true for extra diagnostic logging

[build]
  base    = "site"
  publish = "public"
  command = "npm run build"
  # Always build the site, regardless of code updates: https://bit.ly/3fxbQO6
  ignore = "sh this-always-fails"
